config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :pics, only: [:create, :destroy]
  resources :backgrounds, only: [:create]
  delete "destroy_all_posts", to: "pics#destroy_all_posts"
  delete "destroy_background", to: "backgrounds#destroy_background"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/background.rb
class Background < ApplicationRecord
  has_one_attached :photo
  validates :photo, presence: true

end

app/models/pic.rb
class Pic < ApplicationRecord
  has_one_attached :photo
  validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :wallets
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  def create
    background = Background.new(background_params)
    if background.img.nil?
      background.img = Background.last.img if Background.last
    end
    background.save
    redirect_to root_path
  end

  def destroy_background
    Background.destroy_all
    redirect_to root_path
  end

  private
  def background_params
    params.require(:background).permit(:img, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Hello world"
    @errors = params[:errors]
    @background = Background.new
  end

  def process_pic
    raise
    params[:post][:file]
    redirect_to root_path
  end


  private

  def permited_params

  end

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  def create
    pic = Pic.new(pic_params)
    pic.save
    # raise
    redirect_to root_path(errors: pic.errors.full_messages)
  end

  def destroy
    pic = Pic.find(params["id"])
    pic.destroy
    redirect_to root_path
  end

  def destroy_all_posts
    Pic.destroy_all
    redirect_to root_path
  end

  private

  def pic_params
    params.require(:pic).permit(:title, :comment, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wxllt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

  </head>

  <body style="<% if Background.last %>background-image: url(<%= cl_image_path Background.last.photo.key %>;<% else %> background-color: rgb(247,247,247) <% end %>;">
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-brand">
    <%= image_tag "panda.jpg", class: "avatar" %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "X", destroy_all_posts_path, :class => "btn btn-danger btn-size", method: "delete" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "panda.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="container">

  <div class="form-container">
    <%= simple_form_for(Pic.new) do |f| %>
      <!-- [...] -->

      <div class="first-info d-flex">
        <%= f.input :title %>
        <%= f.input :comment %>
      </div>
      <div class="d-flex justify-content-around align-items-center">
        <%= f.input :photo, as: :file, label: false %>
        <%= f.submit "Create", :class => "btn btn-primary btn-size" %>
      </div>
    <% if @errors %>
      <p class="text-danger">(must add a picture)</p>


    <% end %>
      <!-- [...] -->
    <% end %>
  </div>



  <!-- <div class="row mt-5"> -->
  <div class="cards-container">

    <% Pic.all.each do |pic| %>


    <div class="card-product mt-5">
      <img src="<%= cl_image_path pic.photo.key %>" />
      <div class="card-product-infos">
        <h2><%= pic.title %></h2>
        <p><%= pic.comment %></p>
      </div>
    </div>
    <div class="text-right pic-delete">
      <%= link_to pic_path(pic), method: "delete", class: "trash-btn" do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>

    <% end %>
  </div>
  <!-- </div> -->

</div>

<div class="my-form">
  <%= simple_form_for(@background) do |f| %>
        <!-- [...] -->
    <div class="d-flex justify-content-around align-items-center">
      <%= f.input :photo, as: :file, label: false %>
      <%= f.hidden_field :img %>
      <%= f.submit "set back", :class => "btn btn-primary btn-size" %>
      <%= link_to "clear", destroy_background_path, :class => "clear-btn btn btn-danger btn-size", method: "delete" %>
    </div>
        <!-- [...] -->
  <% end %>

</div>